### PR TITLE
Added VASSAL engine, ordering change, utf-8 fixes

### PR DESCRIPTION
**Pull request by nikuda**

### CODE REVIEW

**Comment by wonea** [comment]
Looks good, although Visual Pinball is actually a game. Shouldn't that remain so? I understand the logic behind VASSAL but Visual Pinball is different.

**Comment by cxong** [comment]
no I don't think all board games / pinball games should be lumped together. Also I'm not so sure about including board games unless they are a clone of an existing video game. See #69

**Comment by nikuda** [comment]
> Looks good, although Visual Pinball is actually a game. Shouldn't that remain so?

Was there a Visual Pinball game that Visual Pinball is an open source version of? I thought Visual Pinball was the original emulator of actual pinball machines and therefore doesn't have a parent game that it is a remake/clone of.

**Comment by nikuda** [comment]
> no I don't think all board games / pinball games should be lumped together. 

Yea this will be a difficult one, it's a similar problem to ScummVM. Do we list all the games that ScummVM supports or do we just have it's entry as an exception to all other entries. I think ScummVM, VASSAL and Visual Pinball are the ones we should make an exception for until a better solution is found.

> Also I'm not so sure about including board games unless they are a clone of an existing video game.

Me neither, don't have a good answer to this but felt VASSAL might be ok since it's a not a new game but a digital version of existing games. Kind of like Visual Pinball.

**Comment by cxong** [comment]
What about this: put these compilation games/engines into their own list, just as we currently have with remakes/clones?

On that note, we should have links at the top of the page to jump to these lists, maybe as a sidebar. The list is now so long I have trouble finding where the remakes list ends and the clones list begins.

**Comment by wonea** [comment]
I agree with all these points;

- Create separate file compilation items, ScummVM and #326 has been waiting for a place.
- Clones and reimplementations should be better displayed together.

Also Visual Pinball was a game, and should remain listed under that.

https://en.wikipedia.org/wiki/Visual_Pinball

On a side note: wouldn't be cool if the first letter of a game and was listed down the side. Much like browsing through an address book?

[http://www.brianhadaway.com/wp-content/uploads/2011/05/ioslist2.png](url)

**Pull request merged**
