### PR TITLE
Added mostly Amiga & Atari game clones

### PR DESCRIPTION
**Pull request by wonea**

### CODE REVIEW

**Comment by wonea** [comment]
Merge time?

**Comment by piranha** [comment]
Hmmm, why did it start working! I haven't fixed deployment yet. :-))

**Comment by wonea** [comment]
You'd be correct. The merged code has appeared on the live website yet.

**Comment by piranha** [comment]
Yeah, I'm trying to set up automatic deploy and it resists. Give me a day or two please, I really want to sort that out. :)

**Pull request merged**
