### PR TITLE
Added Movie Business clone

### PR DESCRIPTION
**Pull request by wonea**
Couldn't find a Wikipedia or MobyGames page, and contacted the author for help

https://github.com/teruk/movbizz/issues/4#issuecomment-107454052

So linking to Gamebase64

### CODE REVIEW

**Comment by piranha** [comment]
Haha, I've even played and it seems when you advertise through a TV, it can't finish turn. :-)

**Comment by teruk** [comment]
really? can you provide me with more information? I can't recreate this error

**Comment by piranha** [comment]
Well, I created a movie, and then waited for a round, made 1 TV advertising, skipped two rounds and it showed me an error page with text 'Whoops, looks like something went wrong.'

**Comment by teruk** [comment]
It should be fixed now. It had actually nothing to do with the advertisement.

**Comment by piranha** [comment]
Heh, I see. :) Though to be honest I can't understand how am I supposed to make money. All I manage to do is spend all my money on a movie and then it never makes any decent profit. :)

**Comment by wonea** [comment]
Are you trying to make Waterworld? http://en.wikipedia.org/wiki/Waterworld

**Comment by teruk** [comment]
I know the problem, the balancing is still something I have to work on. But you would have the same problem in the original game ;-)

**Pull request merged**
