### PR TITLE
New fixed menu

### PR DESCRIPTION
**Pull request by nikuda**
Not having to scroll up to the tags clouds / filter helps

screen shot 2017-01-10 at 1 39 33 pm

Added filtering by "new", "added", or "updated".

screen shot 2017-01-10 at 1 39 09 pm

Cleaned up html, mobile view.

### CODE REVIEW

**Comment by wonea** [comment]
I like it but want to try it out first. @piranha what do you think?

**Comment by wonea** [comment]
Thanks! Is there any chance we could make the menu drop down sticky? Have a little pin icon on it?

**Comment by nikuda** [comment]
Sounds good. I'm not 100% that this is the final solution but it's a step in the right direction. We could also merge it onto a new 'dev' branch and collectively improve it from there if it meets the bare minimum of improvement. 

I'll move 4b8ec92da3bd37823dfc6a3248347eb5348ef04e into a separate PR as that can be merged straight away, it cleans up a lot the HTML structure.

**Comment by nikuda** [comment]
Ah never mind, should've refreshed this page before commenting. 

Think we can make the menu sticky with :focus. 🤔

**Pull request merged**
