### PR TITLE
Added Bt Builder. Updated the information on Ostrich Riders.

### PR DESCRIPTION
**Pull request by dulsi**

### CODE REVIEW

**Comment by wonea** [comment]
Please add the licence to Bt Builder, which is GPL;

info: active development, C++, GPL3

https://github.com/dulsi/btbuilder/blob/master/COPYING
Thanks!

**Comment by dulsi** [comment]
Added the license info.

**Comment by piranha** [comment]
@wonea you know you can merge when you think everything is ok, right? :)

**Comment by piranha** [comment]
@dulsi thanks!

**Comment by wonea** [comment]
@piranha I know, I should do it more often!

**Pull request merged**
