### PR TITLE
Game meta, data validation and schema

### PR DESCRIPTION
**Pull request by nikuda**
Using `pykwalify` library to make sure the structure of **games.yaml** is valid. It picked up a lot of errors even in this basic form - see **schema.yaml**. More validating can be added later through `pykwalify` [extensions](http://pykwalify.readthedocs.io/en/unstable/extensions.html).

Some of the erors picked up in `game` structure :

```
...
 - Key 'image' was not defined. Path: '/95/clones/0'.
 - Key 'ststus' was not defined. Path: '/106/clones/0'.
 - Key 'names' was not defined. Path: '/127/clones/0'.
 - Key 'licence' was not defined. Path: '/205/clones/2'.
 - Key 'image' was not defined. Path: '/225/clones/0'.
 - Key 'lang:' was not defined. Path: '/232/clones/1'.
 - Key 'licence' was not defined. Path: '/248/clones/0'.
 - Key 'licence' was not defined. Path: '/270/clones/0'.
 - Key 'stats' was not defined. Path: '/335/clones/2'.
 - Key 'licence' was not defined. Path: '/377/clones/0'.
 - Key 'image' was not defined. Path: '/447/reimplementations/0'.: Path: '/'>
```

With `status` constrained to `[complete, active, sporadic, halted]`:
```
...
 - Enum 'active (not playable yet)' does not exist. Path: '/101/reimplementations/0/status'.
 - Enum 'not playable' does not exist. Path: '/115/clones/1/status'.
 - Enum 'active (not playable, needs game data)' does not exist. Path: '/124/clones/1/status'.
 - Enum 'playable' does not exist. Path: '/137/clones/0/status'.
 - Enum 'halted (seems to be playable)' does not exist. Path: '/201/clones/2/status'.
 - Enum 'sporadic (not playable yet)' does not exist. Path: '/216/clones/0/status'.
 - Enum 'halted (basic game)' does not exist. Path: '/219/clones/0/status'.
 - Enum 'halted (or very sporadic) (playable)' does not exist. Path: '/262/clones/2/status'.
 - Enum 'active (alpha, playable)' does not exist. Path: '/267/clones/0/status'.
 - Enum 'status unavailable' does not exist. Path: '/275/clones/0/status'.
 - Enum 'active (required original files)' does not exist. Path: '/307/clones/1/status'.
 - Enum 'playable' does not exist. Path: '/312/clones/0/status'.: Path: '/'>
```

Related: #30 
Closes: #336 #353 #360

### CODE REVIEW

**Comment by cxong** [comment]
huh, I didn't realise people were using `status` for both development status and playable status! Perhaps they should be separate fields. That should simplify the schema. Although I'm sure people will want to put custom playability values in, like "single player only", "some maps broken".

**Comment by nikuda** [comment]
> Perhaps they should be separate fields. 

I'm about to push a change for that ☺️ 

> Although I'm sure people will want to put custom playability values in, like "single player only", "some maps broken".

I think we should put this kind of misc information into the `info` key.

**Comment by cxong** [comment]
>> Although I'm sure people will want to put custom playability values in, like "single player only", "some maps broken".

> I think we should put this kind of misc information into the `info` key.

Good idea; it's something to watch out for though, because it means playability isn't a simple true/false value, there needs to be a 'partial' option. Depending on who you ask, a game isn't playable unless all of it is playable, or it's playable as long as a small portion of it is.

**Comment by nikuda** [comment]
New schema: 

```yaml
status: playable | unplayable
development: very active | complete | active | sporadic | halted
```

If we try to add `status: sometimes playable` we get:

```
 - Enum 'sometimes playable' does not exist. Path: '/428/reimplementations/2/status'
```

Or if you try to add `development: playable`:

```
- Enum 'playable' does not exist. Path: '/429/reimplementations/0/development'
```

This gets us a bit closer to https://github.com/piranha/osgameclones/issues/30#issuecomment-40033883

**Comment by nikuda** [comment]
>there needs to be a 'partial' option

How about

```yaml
status: playable | semi-playable | unplayable
``` 
or 

```yaml 
status: complete | playable | unplayable
```
I prefer the `complete` value to indicate that all of the game is playable, that it is feature complete. Some variant of `semi-playable` is ok too.

**Comment by cxong** [comment]
- I think now that it's split, `playable` is a better name than `status`
- Now that I think more about it, semi-playability is only clear for perfect clones or those that use original game data. For "inspired by" games, it's not clear, and probably depends on that project's goals more than the original game. So I guess playable will be `playable`/`unplayable` most of the time, so I like your first option better - `semi-playable`

**Comment by nikuda** [comment]
Cool, changed status schema to

```yaml
status: playable | semi-playable | unplayable
```

**Comment by nikuda** [comment]
I think if we change the `status` key to `playable` then maybe this schema would be more suited?

```yaml
playable: yes | partial | no
```

Or something along those lines...

**Comment by nikuda** [comment]
Ready for review/merge. 

This PR fixes a ton of inconsistencies/errors in games.yaml, some of the bigger changes:

* status: 592d7b8340ad3aba07549b5d3d38c98953b64577
* development: 63fa5d416ed2bd09708de2ae66e11ff4e1cb6533
* license: bebe36cc9a1531efb52bab0d407620ebfb15b7aa

Validation:

screen shot 2016-10-07 at 11 27 43 pm

**Comment by nikuda** [comment]
* Added meta key
* Added genre/theme validation
* Genre/theme shows up next to game title like the other tags
* Added Genre tag cloud below the Language tag cloud

Genre/theme info from www.giantbomb.com/games

Closes #353 and #360

screen shot 2016-10-08 at 6 57 59 pm

**Comment by nikuda** [comment]
Most of the youtube embed code was broken, fixed by:

* Removing raw embed support
* Adding youtube embeds based on youtube video id
* Adding vimeo embeds based on vimeo video id
* Making large images fit the content area

Now all the 30+ youtube videos are working again ✨

**Comment by nikuda** [comment]
Added subgenres

```yaml
- name: C-Dogs
  meta:
    genre: [Action, Shoot 'Em Up]
    subgenre: [Run and gun]
  clones:
    - name: C-Dogs SDL
  ...
```

Thoughts? @cxong @wonea @piranha

**Comment by wonea** [comment]
Thanks for this, lets run with it.

**Comment by wonea** [comment]
Also the template needs to be changed to new people submit issues & pull requests

**Comment by piranha** [comment]
Wow, that's pretty cool what you did here!

**Pull request merged**
