### PR TITLE
Dark Theme #426

### PR DESCRIPTION
**Pull request by JG916**

### CODE REVIEW

**Comment by wonea** [comment]
Thanks, its a good start

**Comment by wonea** [comment]
Could we have the dark theme text indented hard right

image

The filters drop downs need the theme applied

image

Could we remember whether the theme has been applied, a cookie or session variable?

**Comment by JG916** [comment]
Just made another pull request for the three fixes.

**Comment by OvermindDL1** [comment]
> a cookie

:+1:  on this specifically

**Pull request merged**
