### PR TITLE
added 'Mice Men: Remix'

### PR DESCRIPTION
**Pull request by synkarius**
This pull request is to add my remake of Mice Men (original at https://archive.org/details/MiceMen_1020 ) to the database.

### CODE REVIEW

**Comment by cxong** [comment]
This alone will not make the clone appear in the list; the `games/originals/m.yaml` also needs an entry for the original game "Mice Men"

**Comment by synkarius** [comment]
@cxong Thanks you. I have updated `games/originals/m.yaml`.

**Comment by nikuda** [comment]
Fixed conflicts in #528. Thanks again @synkarius. 👍

**Comment by synkarius** [comment]
@nikuda Thanks for fixing that. I see how the two lists work now.

**Pull request closed without merging**
