### PR TITLE
Add darkFO to fallout 2 clones

### PR DESCRIPTION
**Pull request by hhirsch**

### CODE REVIEW

**Comment by wonea** [comment]
Missing the licence - Apache.

https://github.com/darkf/darkfo/blob/master/LICENSE.txt

**Comment by hhirsch** [comment]
@wonea Done.

**Comment by wonea** [comment]
Sorry to be a pain, but could you add the data added. This is so it's highlighted as new when the website is updated. Thanks!

**Comment by hhirsch** [comment]
@wonea Done

**Comment by hhirsch** [comment]
@wonea Added the data. You can pull now.

**Comment by hhirsch** [comment]
@piranha @wonea Thanks.

**Comment by piranha** [comment]
Thanks to you! :-) :+1:

**Pull request merged**
