### PR TITLE
Added The Battle for Wesnoth

### PR DESCRIPTION
**Pull request by absorber**
My first PR of the year. Happy 2016 :)

### CODE REVIEW

**Comment by wonea** [comment]
Thank you. Battle for Wesnoth cannot be a clone of itself. According to Wikipedia's article it could be seen as an reimplementation of Masters of Monsters & Warsong.

https://en.wikipedia.org/wiki/The_Battle_for_Wesnoth

**Comment by absorber** [comment]
@wonea I've checked out the gameplay of [Masters of Monsters](https://www.youtube.com/watch?v=Ky0hrCdzrUM) and it does look very similar. The only difference I've noticed is that the "battle mode" is not included in The Battle for Wesnoth and is done all in the "map" interface.

I've done a new commit on this branch, is it better now?

**Comment by wonea** [comment]
Looking better, one more more correction. Info should contain code details.

info: active development, C++ & Lua, GPL2

**Comment by absorber** [comment]
@wonea I've updated The Battle For Wesnoth info and also made a new [PR](https://github.com/piranha/osgameclones/pull/253) in which the `info` field example from `README.md` so that new contributors can add relevant info from the start.

**Comment by piranha** [comment]
Cool, thanks! That's quite a list though. :-)

**Pull request merged**
