### PR TITLE
New game additions

### LINKED ISSUE #414: Frontier First Encounters remake
https://en.wikipedia.org/wiki/Frontier:_First_Encounters

jffe
https://github.com/videogamepreservation/jjffe

GLFFE - Nic Mod
http://nic.dnsalias.com/FFE.html

### PR DESCRIPTION
**Pull request by wonea**
Fixes #414 #415 #416

### CODE REVIEW

**Comment by OvermindDL1** [comment]
For note, sccopter is stated by the author to be a private project and not really for public use, being made for him to test things.  Also its state is minor reading of the sc2 file format and displaying of the tiles, it can do nothing else as of it, thus it should probably not be added.

**Comment by cxong** [comment]
But it has an open source license; just need to make sure it doesn't have the playable tag.

**Comment by OvermindDL1** [comment]
> But it has an open source license; just need to make sure it doesn't have the playable tag.

True, but he's implied it is mostly to learn the formats, not necessarily get something playable.  Although potentially someone could make something playable from it in the future once the formats are figured out.

Perhaps there needs to be a 'to-research' tag of some sort?

**Comment by nikuda** [comment]
>Although potentially someone could make something playable from it in the future

FWIW, there are a quite a few of these early-stage projects in the data already.

**Comment by wonea** [comment]
Thanks for the feedback, I've incorporated the changes.

Maybe status should have another entry for research.
status: # One of: research, unplayable, semi-playable, playable

**Pull request merged**
