### PR TITLE
More games added

### LINKED ISSUE #149: Ace of Spades
OpenSpades ( https://sites.google.com/a/yvt.jp/openspades/downloads ), an open alternative to Ace of Spades

### PR DESCRIPTION
**Pull request by wonea**
Fixes #149 & #150

### CODE REVIEW

**Comment by wonea** [comment]
Okay, I'm done for now.

**Comment by wonea** [comment]
Okay, better finish now.

**Comment by piranha** [comment]
Canabalt-iOS is not a clone, it's an exact source of the game, isn't it?

**Comment by wonea** [comment]
Originally, there has been a lot of activity since it was open sourced. Noticed a pull request to update it for XCode 4

**Comment by piranha** [comment]
Yeah, but still, it's not a clone... :)

**Comment by AGNUcius** [comment]
Hey all, I've been archiving links to Open Source video games for a while
now.

I am considering using the data from OSGameClones to make a more complete
list.

Just wondering if there are any plans to expand the scope of this project
to all Open Source games.

Thanks,
Patrick Anderson
My current list: http://crosscrowdpredictiveproduction.github.io/game.htm

**Comment by wonea** [comment]
Wow, that's an impressive list. Love the commentary.

**Comment by piranha** [comment]
Making an informational project about all open source games is certainly a good idea, but then it would be much bigger than OSGC, requiring much more time to maintain and curate the content - especially given that quite a lot of the games wouldn't have external sources (like Wikipedia) to describe them well, and having descriptions would help.

So on one hand I like the idea, on the other - I'm afraid I'm too short on time to make a viable take on that.

I'm wondering how could we handle that, if we decide to go that road? Single YAML as a database would be really hard to manage. I guess we could split in a few files, but how would we divide them? One alternative coming to mind is standard rdbms-backed site, but that would be an overkill and much more painful to maintain (OSGC is literally 0 upkeep right now).

And then the interface. Any thoughts about the interface?

If we could decide on those points, I guess we could convert the project into 'open source games catalogue' (haha, still osgc :)), and then osgameclones.com would just display a subset of games, or something like that. :)

**Comment by wonea** [comment]
I think we should really make sure we reference Wikipedia. It's a good bar to cross, I don't mind creating the pages as required (have 6 pages needing creation at the moment).

'open source games catalogue' is a good idea. Perhaps we have another node/leaf in the yaml to sit alongside clones / reimplemention - original. Keep them in a separate yaml file.

**Pull request merged**
