### PR TITLE
Couple of Construct2 games

### PR DESCRIPTION
**Pull request by wonea**
Asked about source code here

https://github.com/jvlppm/pucpr-ld-parodius/issues/1#issuecomment-107773628

### CODE REVIEW

**Comment by piranha** [comment]
I wonder if we should render `info` through markdown and make `Construct2` a link, because I don't think that's universally understandable. Any thoughts?

**Comment by piranha** [comment]
Or maybe just render it as HTML. So that tags can be used there.

**Comment by wonea** [comment]
Yes, that sounds like a good idea. Love3D could be a similar problem.

**Comment by piranha** [comment]
Turned out it already works so :-)

**Pull request merged**
